In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Zomato Dataset.csv")

In [3]:
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,21:55,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14:55,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,17:30,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,09:20,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19:50,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41

In [4]:
df.shape

(45584, 20)

In [5]:
df.columns

Index(['ID', 'Delivery_person_ID', 'Delivery_person_Age',
       'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 'Order_Date', 'Time_Orderd',
       'Time_Order_picked', 'Weather_conditions', 'Road_traffic_density',
       'Vehicle_condition', 'Type_of_order', 'Type_of_vehicle',
       'multiple_deliveries', 'Festival', 'City', 'Time_taken (min)'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45584 entries, 0 to 45583
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45584 non-null  str
 1   Delivery_person_ID           45584 non-null  str
 2   Delivery_person_Age          43730 non-null  float64
 3   Delivery_person_Ratings      43676 non-null  float64
 4   Restaurant_latitude          45584 non-null  float64
 5   Restaurant_longitude         45584 non-null  float64
 6   Delivery_location_latitude   45584 non-null  float64
 7   Delivery_location_longitude  45584 non-null  float64
 8   Order_Date                   45584 non-null  str
 9   Time_Orderd                  43853 non-null  str
 10  Time_Order_picked            45584 non-null  str
 11  Weather_conditions           44968 non-null  str
 12  Road_traffic_density         44983 non-null  str
 13  Vehicle_condition            45584 non-null  int64
 14  Type_of_order                45584 non-null  str
 15  Type_of_vehicle              45584 non-null  str
 16  multiple_deliveries          44591 non-null  float64
 17  Festival                     45356 non-null  str
 18  City                         44384 non-null  str
 19  Time_taken (min)             45584 non-null  int64
dtypes: float64(7), int64(2), str(11)
memory usage: 7.0 MB

In [7]:
df.isnull().sum()

ID                                0
Delivery_person_ID                0
Delivery_person_Age            1854
Delivery_person_Ratings        1908
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                    1731
Time_Order_picked                 0
Weather_conditions              616
Road_traffic_density            601
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries             993
Festival                        228
City                           1200
Time_taken (min)                  0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
missing_report = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (df.isnull().sum() / len(df)) * 100
})

missing_report = missing_report[missing_report["Missing_Count"] > 0]

missing_report.sort_values(
    by="Missing_Percentage",
    ascending=False
)

                         Missing_Count  Missing_Percentage
Delivery_person_Ratings           1908            4.185679
Delivery_person_Age               1854            4.067217
Time_Orderd                       1731            3.797385
City                              1200            2.632503
multiple_deliveries                993            2.178396
Weather_conditions                 616            1.351351
Road_traffic_density               601            1.318445
Festival                           228            0.500176

In [10]:
df["Delivery_person_Age"].describe()

count    43730.000000
mean        29.566911
std          5.815064
min         15.000000
25%         25.000000
50%         30.000000
75%         35.000000
max         50.000000
Name: Delivery_person_Age, dtype: float64

In [11]:
df["Delivery_person_Age"].value_counts().sort_index()

Delivery_person_Age
15.0      38
20.0    2136
21.0    2153
22.0    2194
23.0    2086
24.0    2210
25.0    2174
26.0    2159
27.0    2150
28.0    2179
29.0    2191
30.0    2226
31.0    2120
32.0    2201
33.0    2186
34.0    2165
35.0    2261
36.0    2260
37.0    2226
38.0    2218
39.0    2144
50.0      53
Name: count, dtype: int64

In [12]:
age_median = df["Delivery_person_Age"].median()
age_median

np.float64(30.0)

In [13]:
df["Delivery_person_Age"] = df["Delivery_person_Age"].fillna(age_median)

In [14]:
df["Delivery_person_Age"].isnull().sum()

np.int64(0)

In [15]:
df["Age_was_missing"] = df["Delivery_person_Age"].isna().astype(int)

In [16]:
df = pd.read_csv("Zomato Dataset.csv")

In [17]:
df["Age_was_missing"] = df["Delivery_person_Age"].isna().astype(int)

In [18]:
df["Age_was_missing"].value_counts()

Age_was_missing
0    43730
1     1854
Name: count, dtype: int64

In [19]:
age_median = df["Delivery_person_Age"].median()

df["Delivery_person_Age"] = df["Delivery_person_Age"].fillna(age_median)

In [20]:
age_median = df["Delivery_person_Age"].median()

df["Delivery_person_Age"] = df["Delivery_person_Age"].fillna(age_median)

In [21]:
df["Delivery_person_Age"].isnull().sum()

np.int64(0)

In [22]:
df["Delivery_person_Ratings"].describe()

count    43676.000000
mean         4.633774
std          0.334744
min          1.000000
25%          4.500000
50%          4.700000
75%          4.900000
max          6.000000
Name: Delivery_person_Ratings, dtype: float64

In [23]:
df["Delivery_person_Ratings"].value_counts().sort_index()

Delivery_person_Ratings
1.0      38
2.5      20
2.6      22
2.7      22
2.8      19
2.9      19
3.0       6
3.1      29
3.2      29
3.3      25
3.4      32
3.5     249
3.6     207
3.7     225
3.8     228
3.9     197
4.0    1077
4.1    1430
4.2    1418
4.3    1409
4.4    1360
4.5    3302
4.6    6938
4.7    7140
4.8    7146
4.9    7040
5.0    3996
6.0      53
Name: count, dtype: int64

In [24]:
df[df["Delivery_person_Ratings"] == 6.0][
    ["Delivery_person_ID",
     "Delivery_person_Age",
     "Delivery_person_Ratings",
     "Time_taken (min)"]
].head(10)

,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Time_taken (min)
3577,BANGRES05DEL01,50.0,6.0,25
4705,HYDRES17DEL01,50.0,6.0,27
5160,JAPRES08DEL01,50.0,6.0,20
5353,BANGRES19DEL01,50.0,6.0,18
5642,AGRRES13DEL02,50.0,6.0,20
6385,JAPRES06DEL02,50.0,6.0,20
7022,MYSRES15DEL02,50.0,6.0,14
7672,VADRES09DEL01,50.0,6.0,22
9490,BANGRES010DEL01,50.0,6.0,17
9526,RANCHIRES13DEL01,50.0,6.0,32

In [25]:
df.groupby("Delivery_person_Ratings")["Delivery_person_Age"].agg(
    ["count", "mean", "min", "max"]
)

                         count       mean   min   max
Delivery_person_Ratings
1.0                         38  15.000000  15.0  15.0
2.5                         20  24.550000  20.0  29.0
2.6                         22  23.363636  20.0  29.0
2.7                         22  24.727273  20.0  29.0
2.8                         19  24.684211  20.0  29.0
2.9                         19  24.684211  20.0  29.0
3.0                          6  34.166667  30.0  39.0
3.1                         29  26.000000  20.0  39.0
3.2                         29  26.689655  20.0  38.0
3.3                         25  28.040000  22.0  37.0
3.4                         32  29.125000  21.0  39.0
3.5                        249  32.702811  20.0  39.0
3.6                        207  33.685990  20.0  39.0
3.7                        225  33.173333  20.0  39.0
3.8                        228  33.644737  20.0  39.0
3.9                        197  33.000000  20.0  39.0
4.0                       1077  31.228412  20.0  39.0
4.1                       1430  31.411189  20.0  39.0
4.2                       1418  31.340621  20.0  39.0
4.3                       1409  31.526615  20.0  39.0
4.4                       1360  31.383824  20.0  39.0
4.5                       3302  29.001211  20.0  39.0
4.6                       6938  29.123667  20.0  39.0
4.7                       7140  29.058263  20.0  39.0
4.8                       7146  29.159250  20.0  39.0
4.9                       7040  29.074006  20.0  39.0
5.0                       3996  29.310561  20.0  39.0
6.0                         53  50.000000  50.0  50.0

In [26]:
df[df["Delivery_person_Ratings"] == 6.0][
    ["Delivery_person_Age", "Delivery_person_Ratings"]
].value_counts()

Delivery_person_Age  Delivery_person_Ratings
50.0                 6.0                        53
Name: count, dtype: int64

In [27]:
df[df["Delivery_person_Age"] == 50][
    ["Delivery_person_Age", "Delivery_person_Ratings"]
].value_counts()

Delivery_person_Age  Delivery_person_Ratings
50.0                 6.0                        53
Name: count, dtype: int64

In [28]:
df["Rating_was_missing"] = df["Delivery_person_Ratings"].isna().astype(int)

In [29]:
df["Rating_was_missing"].value_counts()

Rating_was_missing
0    43676
1     1908
Name: count, dtype: int64

In [30]:
rating_median = df["Delivery_person_Ratings"].median()
rating_median

np.float64(4.7)

In [31]:
df["Delivery_person_Ratings"].isnull().sum()

np.int64(1908)

In [32]:
df["Delivery_person_Ratings"].describe()

count    43676.000000
mean         4.633774
std          0.334744
min          1.000000
25%          4.500000
50%          4.700000
75%          4.900000
max          6.000000
Name: Delivery_person_Ratings, dtype: float64

In [33]:
df["Time_Orderd"].head(20)

0     21:55
1     14:55
2     17:30
3     09:20
4     19:50
5     20:25
6     14:55
7     20:30
8     20:40
9     21:15
10    20:20
11    22:30
12    08:15
13    19:30
14    12:25
15    18:35
16    20:35
17    23:20
18    21:20
19    23:35
Name: Time_Orderd, dtype: str

In [34]:
df["Time_Orderd"].dtype

In [35]:
df[df["Time_Orderd"].isna()][
    ["Order_Date", "Time_Orderd", "Time_Order_picked", "Time_taken (min)"]
].head(10)

     Order_Date Time_Orderd Time_Order_picked  Time_taken (min)
33   06-04-2022         NaN             18:35                33
65   11-03-2022         NaN             15:30                19
111  02-04-2022         NaN             18:25                25
131  09-03-2022         NaN             23:40                19
170  12-03-2022         NaN             17:50                43
222  02-03-2022         NaN             20:50                24
241  08-03-2022         NaN             21:25                43
280  05-03-2022         NaN             22:05                12
296  04-04-2022         NaN             19:45                39
322  05-03-2022         NaN             22:40                26

In [36]:
df["Order_time_was_missing"] = df["Time_Orderd"].isna().astype(int)

In [37]:
df["Order_time_was_missing"].value_counts()

Order_time_was_missing
0    43853
1     1731
Name: count, dtype: int64

In [38]:
df[df["Time_Orderd"].isna()]["Time_Order_picked"].isna().sum()

np.int64(0)

In [39]:
df[["Time_Orderd", "Time_Order_picked"]].isnull().sum()

Time_Orderd          1731
Time_Order_picked       0
dtype: int64

In [40]:
df[df["Time_Orderd"].isna()]["Time_Order_picked"].isna().sum()

np.int64(0)

In [41]:
df[["Time_Orderd", "Time_Order_picked"]].isnull().sum()

Time_Orderd          1731
Time_Order_picked       0
dtype: int64

In [42]:
df["City"].value_counts(dropna=False)

City
Metropolitian    34087
Urban            10133
NaN               1200
Semi-Urban         164
Name: count, dtype: int64

In [43]:
df["City"].unique()

<StringArray>
['Metropolitian', 'Urban', 'Semi-Urban', nan]
Length: 4, dtype: str

In [44]:
df["City_was_missing"] = df["City"].isna().astype(int)

In [45]:
df["City"] = df["City"].fillna("Unknown")

In [46]:
df["City"].value_counts(dropna=False)

City
Metropolitian    34087
Urban            10133
Unknown           1200
Semi-Urban         164
Name: count, dtype: int64

In [47]:
df["multiple_deliveries"].value_counts(dropna=False).sort_index()

multiple_deliveries
0.0    14094
1.0    28151
2.0     1985
3.0      361
NaN      993
Name: count, dtype: int64

In [48]:
df["multiple_deliveries"].describe()

count    44591.000000
mean         0.744635
std          0.572510
min          0.000000
25%          0.000000
50%          1.000000
75%          1.000000
max          3.000000
Name: multiple_deliveries, dtype: float64

In [49]:
df["Multiple_deliveries_was_missing"] = df["multiple_deliveries"].isna().astype(int)

In [50]:
multiple_median = df["multiple_deliveries"].median()
multiple_median

np.float64(1.0)

In [51]:
df["multiple_deliveries"] = df["multiple_deliveries"].fillna(multiple_median)

In [52]:
df["multiple_deliveries"].isnull().sum()

np.int64(0)

In [53]:
df["Weather_conditions"].value_counts(dropna=False)

Weather_conditions
Fog           7653
Stormy        7584
Cloudy        7533
Sandstorms    7494
Windy         7422
Sunny         7282
NaN            616
Name: count, dtype: int64

In [54]:
df.groupby("Weather_conditions")["Time_taken (min)"].agg(
    ["count", "mean", "median"]
).round(2)

                    count   mean  median
Weather_conditions
Cloudy               7533  28.92    28.0
Fog                  7653  28.91    28.0
Sandstorms           7494  25.88    26.0
Stormy               7584  25.87    26.0
Sunny                7282  21.86    20.0
Windy                7422  26.12    26.0

In [55]:
df["Weather_was_missing"] = df["Weather_conditions"].isna().astype(int)

In [56]:
df["Weather_conditions"] = df["Weather_conditions"].fillna("Unknown")

In [57]:
df["Weather_conditions"].value_counts(dropna=False)

Weather_conditions
Fog           7653
Stormy        7584
Cloudy        7533
Sandstorms    7494
Windy         7422
Sunny         7282
Unknown        616
Name: count, dtype: int64

In [58]:
df["Road_traffic_density"].value_counts(dropna=False)

Road_traffic_density
Low       15476
Jam       14139
Medium    10945
High       4423
NaN         601
Name: count, dtype: int64

In [59]:
df.groupby("Road_traffic_density")["Time_taken (min)"].agg(
    ["count", "mean", "median"]
).round(2)

                      count   mean  median
Road_traffic_density
High                   4423  27.24    27.0
Jam                   14139  31.18    31.0
Low                   15476  21.27    20.0
Medium                10945  26.70    27.0

In [60]:
df["Traffic_was_missing"] = df["Road_traffic_density"].isna().astype(int)

In [61]:
df["Road_traffic_density"] = df["Road_traffic_density"].fillna("Unknown")

In [62]:
df["Road_traffic_density"].value_counts(dropna=False)

Road_traffic_density
Low        15476
Jam        14139
Medium     10945
High        4423
Unknown      601
Name: count, dtype: int64

In [63]:
df["Festival"].value_counts(dropna=False)

Festival
No     44460
Yes      896
NaN      228
Name: count, dtype: int64

In [64]:
df.groupby("Festival")["Time_taken (min)"].agg(
    ["count", "mean", "median"]
).round(2)

          count   mean  median
Festival
No        44460  25.98    25.0
Yes         896  45.52    45.0

In [65]:
df["Festival_was_missing"] = df["Festival"].isna().astype(int)

df["Festival"] = df["Festival"].fillna("Unknown")

In [66]:
df["Festival"].value_counts(dropna=False)

Festival
No         44460
Yes          896
Unknown      228
Name: count, dtype: int64

In [67]:
df.isnull().sum()

ID                                    0
Delivery_person_ID                    0
Delivery_person_Age                   0
Delivery_person_Ratings            1908
Restaurant_latitude                   0
Restaurant_longitude                  0
Delivery_location_latitude            0
Delivery_location_longitude           0
Order_Date                            0
Time_Orderd                        1731
Time_Order_picked                     0
Weather_conditions                    0
Road_traffic_density                  0
Vehicle_condition                     0
Type_of_order                         0
Type_of_vehicle                       0
multiple_deliveries                   0
Festival                              0
City                                  0
Time_taken (min)                      0
Age_was_missing                       0
Rating_was_missing                    0
Order_time_was_missing                0
City_was_missing                      0
Multiple_deliveries_was_missing       0
Weather_was_missing                   0
Traffic_was_missing                   0
Festival_was_missing                  0
dtype: int64

In [68]:
df["Order_Date"] = pd.to_datetime(
    df["Order_Date"],
    format="%d-%m-%Y"
)

In [69]:
df["Order_Date"].dtype

dtype('<M8[us]')

In [70]:
df["Order_Date"].head()

0   2022-02-12
1   2022-02-13
2   2022-03-04
3   2022-02-13
4   2022-02-14
Name: Order_Date, dtype: datetime64[us]

In [71]:
df[["Time_Orderd", "Time_Order_picked"]].head(20)

   Time_Orderd Time_Order_picked
0        21:55             22:10
1        14:55             15:05
2        17:30             17:40
3        09:20             09:30
4        19:50             20:05
5        20:25             20:35
6        14:55             15:10
7        20:30             20:40
8        20:40             20:50
9        21:15             21:30
10       20:20             20:25
11       22:30             22:45
12       08:15             08:30
13       19:30             19:45
14       12:25             12:30
15       18:35             18:50
16       20:35             20:40
17       23:20             23:30
18       21:20             21:35
19       23:35             23:45

In [72]:
print("Order time type:", df["Time_Orderd"].dtype)
print("Pickup time type:", df["Time_Order_picked"].dtype)

print("Missing Order Time:", df["Time_Orderd"].isna().sum())
print("Missing Pickup Time:", df["Time_Order_picked"].isna().sum())

Order time type: str
Pickup time type: str
Missing Order Time: 1731
Missing Pickup Time: 0

In [73]:
df["Time_Orderd"].dropna().astype(str).str.match(
    r"^\d{2}:\d{2}$"
).value_counts()

Time_Orderd
True     39785
False     4068
Name: count, dtype: int64

In [74]:
df["Time_Order_picked"].dropna().astype(str).str.match(
    r"^\d{2}:\d{2}$"
).value_counts()

Time_Order_picked
True     40577
False     5007
Name: count, dtype: int64

In [76]:
mask_order = (
    df["Time_Orderd"].notna() &
    ~df["Time_Orderd"].astype(str).str.match(r"^\d{2}:\d{2}$")
)

df.loc[mask_order, "Time_Orderd"].value_counts().head(20)

Time_Orderd
0.833333333    449
1              430
0.791666667    424
0.958333333    422
0.875          409
0.916666667    404
0.75           402
0.416666667    211
0.458333333    193
0.5            189
0.375          177
0.625           86
0.541666667     79
0.583333333     74
0.708333333     66
0.666666667     53
Name: count, dtype: int64

In [77]:
mask_pickup = (
    df["Time_Order_picked"].notna() &
    ~df["Time_Order_picked"].astype(str).str.match(r"^\d{2}:\d{2}$")
)

df.loc[mask_pickup, "Time_Order_picked"].value_counts().head(20)

Time_Order_picked
0.833333333    452
1              440
24:05:00       435
0.916666667    430
0.75           422
0.875          416
0.958333333    411
0.791666667    403
24:10:00       280
0.375          201
0.416666667    194
0.5            188
24:15:00       165
0.458333333    148
0.625          100
0.666666667     91
0.541666667     83
0.583333333     82
0.708333333     66
Name: count, dtype: int64

In [78]:
def clean_time(value):
    if pd.isna(value):
        return pd.NaT

    value = str(value).strip()

    # Normal HH:MM time
    if ":" in value:
        return pd.to_datetime(value, format="%H:%M", errors="coerce").time()

    # Excel fractional-day time
    try:
        fraction = float(value)

        if 0 <= fraction < 1:
            total_minutes = round(fraction * 24 * 60)
            hours = (total_minutes // 60) % 24
            minutes = total_minutes % 60

            return pd.Timestamp(
                year=2000,
                month=1,
                day=1,
                hour=hours,
                minute=minutes
            ).time()

    except ValueError:
        pass

    return pd.NaT

In [79]:
print(clean_time("21:55"))
print(clean_time("0.5"))
print(clean_time("0.75"))
print(clean_time("0.875"))

21:55:00
12:00:00
18:00:00
21:00:00

In [86]:
from datetime import time

def clean_time(value):
    if pd.isna(value):
        return None

    value = str(value).strip()

    if ":" in value:
        try:
            return pd.to_datetime(
                value,
                format="%H:%M",
                errors="raise"
            ).time()
        except:
            return None

    try:
        fraction = float(value)

        if 0 <= fraction < 1:
            total_minutes = round(fraction * 1440)
            hours = (total_minutes // 60) % 24
            minutes = total_minutes % 60

            return time(hours, minutes)

    except:
        return None

    return None

In [87]:
print(clean_time("21:55"))
print(clean_time("0.5"))
print(clean_time("0.75"))
print(clean_time("0.875"))

21:55:00
12:00:00
18:00:00
21:00:00

In [88]:
df["Time_Orderd_Clean"] = df["Time_Orderd"].apply(clean_time)

df["Time_Order_picked_Clean"] = df["Time_Order_picked"].apply(clean_time)

In [89]:
print("Original Order missing:", df["Time_Orderd"].isna().sum())
print("Clean Order missing:", df["Time_Orderd_Clean"].isna().sum())

print("Original Pickup missing:", df["Time_Order_picked"].isna().sum())
print("Clean Pickup missing:", df["Time_Order_picked_Clean"].isna().sum())

Original Order missing: 1731
Clean Order missing: 2161
Original Pickup missing: 0
Clean Pickup missing: 1320

In [90]:
failed_order = df[
    df["Time_Orderd"].notna() &
    df["Time_Orderd_Clean"].isna()
]["Time_Orderd"]

failed_order.value_counts().head(20)

Time_Orderd
1    430
Name: count, dtype: int64

In [91]:
failed_pickup = df[
    df["Time_Order_picked"].notna() &
    df["Time_Order_picked_Clean"].isna()
]["Time_Order_picked"]

failed_pickup.value_counts().head(20)

Time_Order_picked
1           440
24:05:00    435
24:10:00    280
24:15:00    165
Name: count, dtype: int64

In [92]:
def make_datetime(date_value, time_value):
    if pd.isna(time_value):
        return pd.NaT

    base_date = pd.Timestamp(date_value).normalize()
    value = str(time_value).strip()

    try:
        # Case 1: Excel fractional-day value
        if ":" not in value:
            fraction = float(value)

            if 0 <= fraction <= 1:
                return base_date + pd.to_timedelta(
                    fraction * 24,
                    unit="h"
                )

        # Case 2: HH:MM or HH:MM:SS
        parts = value.split(":")

        hour = int(parts[0])
        minute = int(parts[1])
        second = int(float(parts[2])) if len(parts) > 2 else 0

        # timedelta automatically handles 24:05 as next day 00:05
        return (
            base_date
            + pd.Timedelta(hours=hour)
            + pd.Timedelta(minutes=minute)
            + pd.Timedelta(seconds=second)
        )

    except:
        return pd.NaT

In [93]:
df["Order_DateTime"] = df.apply(
    lambda row: make_datetime(
        row["Order_Date"],
        row["Time_Orderd"]
    ),
    axis=1
)

df["Pickup_DateTime"] = df.apply(
    lambda row: make_datetime(
        row["Order_Date"],
        row["Time_Order_picked"]
    ),
    axis=1
)

In [94]:
print("Order datetime missing:",
      df["Order_DateTime"].isna().sum())

print("Pickup datetime missing:",
      df["Pickup_DateTime"].isna().sum())

Order datetime missing: 1731
Pickup datetime missing: 0

In [95]:
df[
    ["Order_Date", "Time_Orderd", "Order_DateTime",
     "Time_Order_picked", "Pickup_DateTime"]
].head(10)

,Order_Date,Time_Orderd,Order_DateTime,Time_Order_picked,Pickup_DateTime
0,2022-02-12,21:55,2022-02-12 21:55:00,22:10,2022-02-12 22:10:00
1,2022-02-13,14:55,2022-02-13 14:55:00,15:05,2022-02-13 15:05:00
2,2022-03-04,17:30,2022-03-04 17:30:00,17:40,2022-03-04 17:40:00
3,2022-02-13,09:20,2022-02-13 09:20:00,09:30,2022-02-13 09:30:00
4,2022-02-14,19:50,2022-02-14 19:50:00,20:05,2022-02-14 20:05:00
5,2022-04-02,20:25,2022-04-02 20:25:00,20:35,2022-04-02 20:35:00
6,2022-03-01,14:55,2022-03-01 14:55:00,15:10,2022-03-01 15:10:00
7,2022-03-16,20:30,2022-03-16 20:30:00,20:40,2022-03-16 20:40:00
8,2022-03-20,20:40,2022-03-20 20:40:00,20:50,2022-03-20 20:50:00
9,2022-02-15,21:15,2022-02-15 21:15:00,21:30,2022-02-15 21:30:00

In [96]:
df["Pickup_Delay_Minutes"] = (
    (df["Pickup_DateTime"] - df["Order_DateTime"])
    .dt.total_seconds() / 60
)

In [97]:
df["Pickup_Delay_Minutes"].describe()

count    43853.000000
mean         9.989168
std          4.087516
min          5.000000
25%          5.000000
50%         10.000000
75%         15.000000
max         15.000000
Name: Pickup_Delay_Minutes, dtype: float64

In [98]:
df["Pickup_Delay_Minutes"].value_counts().sort_index().head(30)

Pickup_Delay_Minutes
5.0       763
5.0     13156
5.0       782
10.0      805
10.0    12929
10.0      812
15.0      721
15.0    13120
15.0      765
Name: count, dtype: int64

In [99]:
df[df["Pickup_Delay_Minutes"] < 0][
    ["Order_Date", "Time_Orderd", "Time_Order_picked",
     "Order_DateTime", "Pickup_DateTime",
     "Pickup_Delay_Minutes"]
].head(20)

Empty DataFrame
Columns: [Order_Date, Time_Orderd, Time_Order_picked, Order_DateTime, Pickup_DateTime, Pickup_Delay_Minutes]
Index: []

In [100]:
(df["Pickup_Delay_Minutes"] < 0).sum()

np.int64(0)

In [101]:
df.loc[
    df["Pickup_Delay_Minutes"] < 0,
    "Pickup_Delay_Minutes"
].describe()

count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: Pickup_Delay_Minutes, dtype: float64

In [102]:
df["Pickup_Delay_Minutes"].describe(
    percentiles=[0.01, 0.25, 0.5, 0.75, 0.95, 0.99]
)

count    43853.000000
mean         9.989168
std          4.087516
min          5.000000
1%           5.000000
25%          5.000000
50%         10.000000
75%         15.000000
95%         15.000000
99%         15.000000
max         15.000000
Name: Pickup_Delay_Minutes, dtype: float64

In [103]:
df.nlargest(10, "Pickup_Delay_Minutes")[
    ["Time_Orderd", "Time_Order_picked", "Pickup_Delay_Minutes"]
]

     Time_Orderd Time_Order_picked  Pickup_Delay_Minutes
165        18:45       0.791666667                  15.0
180  0.958333333             23:15                  15.0
227  0.458333333             11:15                  15.0
344        21:45       0.916666667                  15.0
452        21:45       0.916666667                  15.0
543  0.958333333             23:15                  15.0
568        09:45       0.416666667                  15.0
633        21:45       0.916666667                  15.0
704  0.833333333             20:15                  15.0
719        12:45       0.541666667                  15.0

In [104]:
print("Dataset Shape:", df.shape)

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDelivery Time Statistics:")
print(df["Time_taken (min)"].describe())

Dataset Shape: (45584, 33)

Duplicate Rows:
0

Missing Values:
ID                                    0
Delivery_person_ID                    0
Delivery_person_Age                   0
Delivery_person_Ratings            1908
Restaurant_latitude                   0
Restaurant_longitude                  0
Delivery_location_latitude            0
Delivery_location_longitude           0
Order_Date                            0
Time_Orderd                        1731
Time_Order_picked                     0
Weather_conditions                    0
Road_traffic_density                  0
Vehicle_condition                     0
Type_of_order                         0
Type_of_vehicle                       0
multiple_deliveries                   0
Festival                              0
City                                  0
Time_taken (min)                      0
Age_was_missing                       0
Rating_was_missing                    0
Order_time_was_missing                0
City_was_missing                      0
Multiple_deliveries_was_missing       0
Weather_was_missing                   0
Traffic_was_missing                   0
Festival_was_missing                  0
Time_Orderd_Clean                  2161
Time_Order_picked_Clean            1320
Order_DateTime                     1731
Pickup_DateTime                       0
Pickup_Delay_Minutes               1731
dtype: int64

Delivery Time Statistics:
count    45584.000000
mean        26.293963
std          9.384298
min         10.000000
25%         19.000000
50%         26.000000
75%         32.000000
max         54.000000
Name: Time_taken (min), dtype: float64

In [105]:
print("Invalid Age:",
      ((df["Delivery_person_Age"] < 18) |
       (df["Delivery_person_Age"] > 60)).sum())

print("Negative Delivery Time:",
      (df["Time_taken (min)"] <= 0).sum())

print("Negative Pickup Delay:",
      (df["Pickup_Delay_Minutes"] < 0).sum())

Invalid Age: 38
Negative Delivery Time: 0
Negative Pickup Delay: 0

In [106]:
df.to_csv(
    "Zomato_Delivery_Cleaned.csv",
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [107]:
import os

print(os.path.exists("Zomato_Delivery_Cleaned.csv"))

True